version: '3.8'

services:
  app:
    build: ./backend
    container_name: student_management_app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: student_management_mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: student_management_frontend
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
